# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'FCI' do

	pod 'GoogleMaps'
        pod 'GooglePlaces'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FCI

  target 'FCITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FCIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
